import { AlertCircle, CheckCircle, Upload } from 'lucide-react';
import React, { useRef, useState } from 'react';
import { Spinner } from '@shared/ui';

interface DocumentUploadFieldProps {
  value: string;
  onChange: (objectKey: string) => void;
  docType: string;
  placeholder?: string;
  accept?: string;
  uploadEndpoint?: string;
}

export default function DocumentUploadField({
  value,
  onChange,
  docType,
  placeholder = "Upload Document",
  accept = "image/*,application/pdf",
  uploadEndpoint = "/api/delivery/verification/upload-url"
}: DocumentUploadFieldProps) {
  const [isUploading, setIsUploading] = useState(false);
  const [error, setError] = useState('');
  const [isDragging, setIsDragging] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const processFile = async (file: File) => {
    if (file.size > 5 * 1024 * 1024) {
      setError('File size should not exceed 5MB');
      return;
    }

    setIsUploading(true);
    setError('');

    try {
      const token = localStorage.getItem('token');
      const uploadUrlQuery = new URLSearchParams({ docType, filetype: file.type }).toString();
      const resData = await window.fetch(import.meta.env.VITE_API_BASE_URL + uploadEndpoint + '?' + uploadUrlQuery, {
        headers: {
          'Authorization': token ? `Bearer ${token}` : '',
          'Accept': 'application/json'
        }
      });
      const res = await resData.json();

      if (!res?.uploadUrl || !res?.objectKey) {
        throw new Error("Failed to get secure upload link.");
      }

      const { uploadUrl, objectKey } = res;

      // Intercept mock URL generated by dev profile in the backend
      if (uploadUrl.includes("mock-upload-url")) {
        await new Promise(resolve => setTimeout(resolve, 500)); // Simulate network delay
        onChange(objectKey);
        setIsUploading(false);
        return;
      }

      // 2. Upload file directly to Cloudflare R2 / S3
      const uploadRes = await window.fetch(uploadUrl, {
        method: 'PUT',
        headers: {
          'Content-Type': file.type
        },
        body: file
      });

      if (!uploadRes.ok) {
        throw new Error(`Upload failed with status: ${uploadRes.status}`);
      }

      // 3. Save the object key
      onChange(objectKey);

    } catch (err: unknown) {
      console.error('Error uploading document:', err);
      const axiosErr = err as { response?: { data?: { message?: string, error?: string } }, message?: string };
      setError(axiosErr.response?.data?.message || axiosErr.response?.data?.error || axiosErr.message || 'Failed to upload document');
    } finally {
      setIsUploading(false);
      if (fileInputRef.current) {
        fileInputRef.current.value = '';
      }
    }
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) processFile(file);
  };

  const handleDragOver = (e: React.DragEvent<HTMLButtonElement>) => {
    e.preventDefault();
    setIsDragging(true);
  };

  const handleDragLeave = (e: React.DragEvent<HTMLButtonElement>) => {
    e.preventDefault();
    setIsDragging(false);
  };

  const handleDrop = (e: React.DragEvent<HTMLButtonElement>) => {
    e.preventDefault();
    setIsDragging(false);
    const file = e.dataTransfer.files?.[0];
    if (file) processFile(file);
  };

  return (
    <div className="w-full">
      <div className="flex items-center space-x-3">
        <button type="button"
          onClick={() => {
            if (!isUploading) {
              setError('');
              fileInputRef.current?.click();
            }
          }}
          onDragOver={handleDragOver}
          onDragLeave={handleDragLeave}
          onDrop={handleDrop}
          className="flex-1 flex flex-col items-center justify-center p-6 rounded-2xl border-2 border-dashed cursor-pointer transition"
          style={{
            // one tinted state per meaning, from the semantic tokens -- which also carry dark
            // mode, so the four `dark:` twins this replaces are gone
            background: isDragging || error
              ? 'var(--color-danger-bg)'
              : value
                ? 'var(--color-success-bg)'
                : 'var(--color-paper-sunken)',
            borderColor: isDragging
              ? 'var(--color-action)'
              : error
                ? 'var(--color-danger-line)'
                : value
                  ? 'var(--color-success-line)'
                  : 'var(--color-paper-line)',
          }}
        >
          {isUploading ? (
            <div className="flex flex-col items-center space-y-2">
              <Spinner size="md" color="var(--color-action)" />
              <span className="text-sm font-medium text-slate-700 dark:text-slate-300">Uploading securely...</span>
            </div>
          ) : value ? (
            <div className="flex flex-col items-center space-y-2">
              <CheckCircle className="h-8 w-8 text-amber-500" />
              <span className="text-sm font-bold text-amber-600 dark:text-amber-400">Document Uploaded</span>
              <span className="text-xs text-slate-500 dark:text-slate-400 text-center px-4 truncate w-full">Click to replace</span>
            </div>
          ) : (
            <div className="flex flex-col items-center space-y-2">
              <div className="h-10 w-10 rounded-full bg-rose-500/10 flex items-center justify-center">
                <Upload className="h-5 w-5 text-rose-500" />
              </div>
              <span className="text-sm font-medium text-slate-700 dark:text-slate-300">
                <span className="font-bold text-rose-600 dark:text-rose-400">Click to upload</span> or drag and drop
              </span>
              <span className="text-xs text-slate-500 dark:text-slate-400">{placeholder} (Max: 5MB)</span>
            </div>
          )}
        </button>
      </div>

      <input
        type="file"
        ref={fileInputRef}
        onChange={handleFileUpload}
        accept={accept}
        className="hidden"
      />

      {error && (
        <div className="mt-2 flex items-center text-[11px] font-medium text-rose-500">
          <AlertCircle className="h-3 w-3 mr-1" /> {error}
        </div>
      )}
    </div>
  );
}
