import js from "@eslint/js";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

import unusedImports from "eslint-plugin-unused-imports";

export default tseslint.config(
  { ignores: ["dist", "src/api/generated/**", "src/types/backend-enums.ts",
              // Regenerated by MSW on every install (package.json "msw".workerDirectory).
              // The 2.15.0 template opens with /* eslint-disable */, which
              // --report-unused-disable-directives then flags. Vendor code, not ours to lint.
              "public/mockServiceWorker.js"] },   // regenerated by scripts/generate-api-types.sh
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: { browser: true },
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
      "unused-imports": unusedImports,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "unused-imports/no-unused-imports": "warn",
      "react-refresh/only-export-components": [
        "warn",
        { allowConstantExport: true },
      ],
      // ---- Debt carried under a ratchet -------------------------------------------------
      // These are real findings, not noise, but there are hundreds of them and fixing them all
      // at once would be a change nobody could review. They are warnings so `npm run lint` is
      // green today, and package.json pins --max-warnings to the current count so the number can
      // only go down. Lowering that number as they are fixed is the whole mechanism; raising it
      // should not pass review.
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-unused-vars": ["warn", {
        argsIgnorePattern: "^_",
        varsIgnorePattern: "^_",
        caughtErrorsIgnorePattern: "^_",
      }],
      "react-hooks/set-state-in-effect": "warn",
      "react-hooks/immutability": "warn",
      "react-hooks/refs": "warn",
      "react-hooks/purity": "warn",

      // ---- Hard rules: these fail the build ---------------------------------------------
      // react-hooks/rules-of-hooks stays an error (from the recommended set): a conditionally
      // called hook is a bug, not debt.
      "no-restricted-syntax": [
        "error",
        {
          // bare `fetch(...)`
          selector: 'CallExpression[callee.name="fetch"]',
          message: 'Raw fetch is forbidden. Use the typed Zodios API client (e.g. identityApi) instead to ensure runtime schema validation and correct headers.',
        },
        {
          // `window.fetch(...)` / `globalThis.fetch(...)` -- the original selector matched only a
          // bare identifier, so writing the member form silently bypassed the ban.
          selector: 'CallExpression[callee.type="MemberExpression"][callee.property.name="fetch"]',
          message: 'Raw fetch is forbidden (including window.fetch/globalThis.fetch). Use the typed Zodios API client instead.',
        },
        {
          selector: 'TemplateLiteral > TemplateElement[value.raw=/\\$/] ~ Identifier[name=/[aA]mount|[tT]otal|[bB]alance|[rR]efund|[qQ]uote|[pP]ayout/]',
          message: 'Do not use $ for currency. Use formatINR from src/shared/money/format.ts.',
        },
        {
          selector: 'CallExpression[callee.property.name="toFixed"][arguments.0.value=2]',
          message: 'Do not use .toFixed(2) for money. Use formatINR from src/shared/money/format.ts.',
        },
        {
          selector: 'CallExpression[callee.property.name="parse"][callee.object.name!="JSON"]',
          message: 'Do not use .parse() on Zod schemas as it throws on failure. Use .safeParse() instead to gracefully handle validation errors.',
        }
      ],
    },
  },
  {
    // Raw fetch is allowed only where no typed client exists or could exist:
    //   - BFF-local routes (/api/logs, /api/config/ui, /olamaps/* proxy) which are not part of
    //     any service's OpenAPI spec and so have no generated Zodios client;
    //   - WebSocket / WebRTC signalling, which is not REST.
    // Every entry below was verified against its call sites on 2026-08-23. The previous list had
    // drifted to paths that no longer exist, which meant it exempted nothing and the rule was
    // instead being bypassed by writing `window.fetch` -- a form the selector did not match.
    files: [
      "src/lib/logger.ts",                                                  // POST /api/logs on the BFF
      "src/contexts/ConfigContext.tsx",                                     // bootstraps config before any client exists
      "src/mocks/**",                                                       // MSW handlers
      "src/features/communication/models/useChatWebSocket.ts",              // WebSocket signalling
      "src/features/communication/models/useWebRTC.ts",                     // WebRTC signalling
      "src/features/catalog/model/menuStore.ts",                            // BFF-proxied menu fetches
      "src/features/catalog/components/customer/CustomerRestaurantCard.tsx",
      "src/features/catalog/components/restaurant/OutletRegistration.tsx",  // /olamaps/* proxy
      "src/features/customer-orders/components/CustomerAddressModal.tsx",   // /olamaps/* proxy
      "src/features/customer-orders/components/CustomerAddressSelectorModal.tsx",
      "src/features/customer-orders/components/CustomerAddressPage.tsx",    // /api/places/geocode on the BFF
      "src/features/kyc/components/DocumentUploadField.tsx",                // presigned-URL upload, not a service API
      "src/features/restaurant-orders/model/useRestaurantOrders.ts"         // missing from OpenAPI spec
    ],
    rules: {
      "no-restricted-syntax": "off"
    }
  },
  {
    files: ["src/shared/money/**/*.ts", "src/shared/money/**/*.tsx"],
    rules: {
      "no-restricted-syntax": "off"
    }
  }
);
