/* tslint:disable */
/* eslint-disable */

export enum ChannelType {
    SMS = "SMS",
    EMAIL = "EMAIL",
    PUSH = "PUSH",
    WHATSAPP = "WHATSAPP",
}

export enum ChargeCategory {
    DELIVERY_FEE = "DELIVERY_FEE",
    PLATFORM_FIXED_FEE = "PLATFORM_FIXED_FEE",
    PLATFORM_BONUS = "PLATFORM_BONUS",
    FOOD_COST = "FOOD_COST",
    SGST = "SGST",
    CGST = "CGST",
    REFUND = "REFUND",
    ORDER_TOTAL = "ORDER_TOTAL",
    AD_IMPRESSION = "AD_IMPRESSION",
    AD_CLICK = "AD_CLICK",
    AD_CONVERSION = "AD_CONVERSION",
    AD_WALLET_TOPUP = "AD_WALLET_TOPUP",
    CLAWBACK = "CLAWBACK",
    PAYOUT_TRANSFER = "PAYOUT_TRANSFER",
    CASH_COLLECTED = "CASH_COLLECTED",
    CASH_REMITTED = "CASH_REMITTED",
    STORE_CREDIT = "STORE_CREDIT",
}

export enum DeliveryStatus {
    PENDING = "PENDING",
    SEARCHING_FOR_DRIVER = "SEARCHING_FOR_DRIVER",
    MANUAL_INTERVENTION_REQUIRED = "MANUAL_INTERVENTION_REQUIRED",
    ASSIGNED = "ASSIGNED",
    AT_RESTAURANT = "AT_RESTAURANT",
    OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY",
    DELIVERED = "DELIVERED",
    CANCELLED = "CANCELLED",
    FAILED = "FAILED",
}

export enum EntityType {
    CUSTOMER = "CUSTOMER",
    RESTAURANT = "RESTAURANT",
    DRIVER = "DRIVER",
    PLATFORM = "PLATFORM",
    ADVERTISER = "ADVERTISER",
}

export enum FaultType {
    PLATFORM_FAULT = "PLATFORM_FAULT",
    RESTAURANT_FAULT = "RESTAURANT_FAULT",
    RIDER_FAULT = "RIDER_FAULT",
    CUSTOMER_FAULT = "CUSTOMER_FAULT",
    UNKNOWN = "UNKNOWN",
}

export enum LedgerAccountType {
    GATEWAY_RECEIVABLE = "GATEWAY_RECEIVABLE",
    CASH_RECEIVABLE = "CASH_RECEIVABLE",
    BANK = "BANK",
    PLATFORM_CLEARING = "PLATFORM_CLEARING",
    PLATFORM_REVENUE = "PLATFORM_REVENUE",
    TAX_PAYABLE = "TAX_PAYABLE",
    PAYOUT_IN_TRANSIT = "PAYOUT_IN_TRANSIT",
    RESTAURANT_PAYABLE = "RESTAURANT_PAYABLE",
    DRIVER_PAYABLE = "DRIVER_PAYABLE",
    CUSTOMER_CREDIT = "CUSTOMER_CREDIT",
    ADVERTISER_PREPAID = "ADVERTISER_PREPAID",
}

export enum Kind {
    EXTERNAL = "EXTERNAL",
    INTERNAL = "INTERNAL",
    PAYABLE = "PAYABLE",
    PREPAID = "PREPAID",
}

export enum OrderStatus {
    CREATED = "CREATED",
    PENDING_ACCEPTANCE = "PENDING_ACCEPTANCE",
    AWAITING_DELAY_APPROVAL = "AWAITING_DELAY_APPROVAL",
    ACCEPTED = "ACCEPTED",
    PREPARING = "PREPARING",
    READY_FOR_PICKUP = "READY_FOR_PICKUP",
    HANDED_OVER = "HANDED_OVER",
    CANCELLED = "CANCELLED",
    CANCELLED_BY_RESTAURANT = "CANCELLED_BY_RESTAURANT",
}

export enum OutboxStatus {
    UNPROCESSED = "UNPROCESSED",
    PROCESSED = "PROCESSED",
    FAILED = "FAILED",
    DLQ = "DLQ",
}

export enum PaymentGateway {
    RAZORPAY = "RAZORPAY",
    CASHFREE = "CASHFREE",
    VYAPAR = "VYAPAR",
}

export enum PaymentMethod {
    CARD = "CARD",
    UPI = "UPI",
    WALLET = "WALLET",
    COD = "COD",
}

export enum RefundDestination {
    ORIGINAL_METHOD = "ORIGINAL_METHOD",
    STORE_CREDIT = "STORE_CREDIT",
    NONE = "NONE",
}

export enum RefundStatus {
    REQUESTED = "REQUESTED",
    PROCESSING = "PROCESSING",
    COMPLETED = "COMPLETED",
    FAILED = "FAILED",
    CANCELLED = "CANCELLED",
}

export enum RoleName {
    CUSTOMER = "CUSTOMER",
    DELIVERY = "DELIVERY",
    RESTAURANT = "RESTAURANT",
    ADMIN = "ADMIN",
}

export enum TransactionDirection {
    CREDIT = "CREDIT",
    DEBIT = "DEBIT",
}

export enum TransactionStatus {
    PENDING = "PENDING",
    SUCCESS = "SUCCESS",
    FAILED = "FAILED",
}

export enum UserRole {
    CUSTOMER = "CUSTOMER",
    RESTAURANT = "RESTAURANT",
    DRIVER = "DRIVER",
    ADMIN = "ADMIN",
    SERVICE = "SERVICE",
}

export enum VehicleClass {
    BICYCLE = "BICYCLE",
    MCWG = "MCWG",
    LMV = "LMV",
    EV_TWO_WHEELER = "EV_TWO_WHEELER",
}

export enum VerificationStatus {
    PENDING = "PENDING",
    APPROVED = "APPROVED",
    VERIFIED = "VERIFIED",
    REJECTED = "REJECTED",
    MANUAL_REVIEW = "MANUAL_REVIEW",
    FAILED = "FAILED",
}

export enum VerificationType {
    GSTIN = "GSTIN",
    PENNY_DROP = "PENNY_DROP",
    PAN = "PAN",
    DRIVING_LICENSE = "DRIVING_LICENSE",
    RC = "RC",
}

export enum WalletEntityType {
    CUSTOMER = "CUSTOMER",
    ADVERTISER = "ADVERTISER",
}
