import { Restaurant, MenuItem } from './types';

export const RESTAURANTS: Restaurant[] = [
  {
    id: 'rest-1',
    name: 'Burger Craft & Co.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
    cuisine: 'Gourmet Burgers, American',
    rating: 4.8,
    reviewsCount: 1240,
    deliveryTime: 25,
    deliveryFee: 2.99,
    tags: ['Burgers', 'Fast Food', 'Beverages'],
    distance: 1.8,
  },
  {
    id: 'rest-2',
    name: 'Bella Italia Pizzeria',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80',
    cuisine: 'Woodfired Pizza, Italian, Pasta',
    rating: 4.7,
    reviewsCount: 850,
    deliveryTime: 35,
    deliveryFee: 3.49,
    tags: ['Pizza', 'Italian', 'Vegetarian'],
    distance: 2.4,
  },
  {
    id: 'rest-3',
    name: 'Sakura Zen Sushi',
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=800&q=80',
    cuisine: 'Japanese, Sushi, Ramen',
    rating: 4.9,
    reviewsCount: 920,
    deliveryTime: 30,
    deliveryFee: 4.00,
    tags: ['Sushi', 'Healthy', 'Japanese'],
    distance: 3.1,
  },
  {
    id: 'rest-4',
    name: 'The Green Bowl Bistro',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
    cuisine: 'Organic Salads, Vegan, Healthy',
    rating: 4.6,
    reviewsCount: 430,
    deliveryTime: 20,
    deliveryFee: 1.99,
    tags: ['Salads', 'Healthy', 'Vegan'],
    distance: 1.2,
  },
  {
    id: 'rest-5',
    name: 'Le Bistro Sweet Paris',
    image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=800&q=80',
    cuisine: 'Desserts, French Patisserie',
    rating: 4.8,
    reviewsCount: 310,
    deliveryTime: 15,
    deliveryFee: 2.50,
    tags: ['Desserts', 'Sweet', 'Bakery'],
    distance: 0.9,
  }
];

export const MENU_ITEMS: Record<string, MenuItem[]> = {
  'rest-1': [
    {
      id: 'menu-1-1',
      name: 'Truffle Umami Burger',
      price: 14.99,
      description: 'Prime Angus beef patty, white truffle aioli, melted swiss cheese, and caramelized forest mushrooms on toasted brioche.',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=400&q=80',
      category: 'Burgers',
      rating: 4.9,
      isVeg: false,
      isAvailable: true,
    },
    {
      id: 'menu-1-2',
      name: 'Crispy Avocado Ranch Burger',
      price: 12.99,
      description: 'Panko-crusted spiced avocado wedge, fresh jalapeño slaw, heirloom tomato, and house dill ranch.',
      image: 'https://images.unsplash.com/photo-1525059696034-4967a8e1dca2?auto=format&fit=crop&w=400&q=80',
      category: 'Burgers',
      rating: 4.7,
      isVeg: true,
      isAvailable: true,
    },
    {
      id: 'menu-1-3',
      name: 'Sweet Potato Waffle Fries',
      price: 5.49,
      description: 'Crisp waffle-cut sweet potato fries dusted with sea salt and smoked paprika, served with honey mustard.',
      image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=400&q=80',
      category: 'Sides',
      rating: 4.8,
      isVeg: true,
      isAvailable: true,
    },
    {
      id: 'menu-1-4',
      name: 'Salted Caramel Milkshake',
      price: 6.99,
      description: 'Creamy Madagascar vanilla bean ice cream blended with artisanal fleur de sel caramel, topped with whipped cream.',
      image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=400&q=80',
      category: 'Beverages',
      rating: 4.9,
      isVeg: true,
      isAvailable: true,
    }
  ],
  'rest-2': [
    {
      id: 'menu-2-1',
      name: 'Burrata & Prosciutto Pizza',
      price: 18.49,
      description: 'San Marzano tomatoes, hand-torn creamy burrata mozzarella, 24-month aged Parma prosciutto, and baby arugula.',
      image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=400&q=80',
      category: 'Pizza',
      rating: 4.9,
      isVeg: false,
      isAvailable: true,
    },
    {
      id: 'menu-2-2',
      name: 'Margherita DOC',
      price: 13.99,
      description: 'The absolute classic. Buffalo mozzarella, organic San Marzano tomato sauce, fresh basil sprigs, and extra virgin olive oil.',
      image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=400&q=80',
      category: 'Pizza',
      rating: 4.8,
      isVeg: true,
      isAvailable: true,
    },
    {
      id: 'menu-2-3',
      name: 'Tuscan Garlic Focaccia',
      price: 6.99,
      description: 'Freshly baked rosemary flatbread rubbed with garlic, roasted sea salt, served with cold-pressed olive oil & balsamic.',
      image: 'https://images.unsplash.com/photo-1549931319-a545dcf3bc73?auto=format&fit=crop&w=400&q=80',
      category: 'Sides',
      rating: 4.6,
      isVeg: true,
      isAvailable: true,
    }
  ],
  'rest-3': [
    {
      id: 'menu-3-1',
      name: 'Signature Dragon Roll',
      price: 16.99,
      description: 'Eel and cucumber inside, layered with premium thin-sliced avocado, tobiko roe, and drizzled with unagi eel sauce.',
      image: 'https://images.unsplash.com/photo-1611143669185-af224c5e3252?auto=format&fit=crop&w=400&q=80',
      category: 'Sushi',
      rating: 4.9,
      isVeg: false,
      isAvailable: true,
    },
    {
      id: 'menu-3-2',
      name: 'Hokkaido Spicy Tuna Temaki',
      price: 14.50,
      description: 'Minced premium yellowfin tuna tossed in spicy sriracha sesame sauce, cucumber matchsticks, and rolled in crisp nori sheets.',
      image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=400&q=80',
      category: 'Sushi',
      rating: 4.8,
      isVeg: false,
      isAvailable: true,
    },
    {
      id: 'menu-3-3',
      name: 'Ceremonial Matcha Iced Tea',
      price: 4.99,
      description: 'Chilled premium stone-ground Uji matcha whisked over ice, lightly sweetened with pure cane nectar.',
      image: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=400&q=80',
      category: 'Beverages',
      rating: 4.7,
      isVeg: true,
      isAvailable: true,
    }
  ],
  'rest-4': [
    {
      id: 'menu-4-1',
      name: 'Quinoa & Avocado Harvest Bowl',
      price: 12.49,
      description: 'Warm organic tricolor quinoa, shredded kale, roasted sweet potato wedges, edamame, Hass avocado, and zesty tahini dressing.',
      image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=400&q=80',
      category: 'Salads',
      rating: 4.7,
      isVeg: true,
      isAvailable: true,
    },
    {
      id: 'menu-4-2',
      name: 'Roasted Beet & Goat Cheese Salad',
      price: 11.99,
      description: 'Ruby red beets, creamy local goat cheese, caramelized walnuts, and crisp baby spinach tossed in white balsamic vinaigrette.',
      image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=400&q=80',
      category: 'Salads',
      rating: 4.5,
      isVeg: true,
      isAvailable: true,
    }
  ],
  'rest-5': [
    {
      id: 'menu-5-1',
      name: 'French Double-Chocolate Soufflé',
      price: 9.99,
      description: 'Decadent baked chocolate soufflé with a molten liquid center, topped with powdered sugar and premium vanilla gelato.',
      image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=400&q=80',
      category: 'Desserts',
      rating: 4.9,
      isVeg: true,
      isAvailable: true,
    },
    {
      id: 'menu-5-2',
      name: 'Classic Berry Crêpe',
      price: 8.50,
      description: 'Paper-thin delicate crêpe stuffed with organic wild strawberries, blueberries, blackberries, and Chantilly cream.',
      image: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?auto=format&fit=crop&w=400&q=80',
      category: 'Desserts',
      rating: 4.8,
      isVeg: true,
      isAvailable: true,
    }
  ]
};
